Test scikit-build-core tiledb-py
conda-forge/tiledb-py-feedstock pull request #224
Opened 2024-07-10 14:52 UTC by dudoslav

This PR is purely for testing purpose in order to see if this PR will work:
https://github.com/TileDB-Inc/TileDB-Py/pull/1988

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2024-07-10 15:09 UTC, jdblischak requested changes
You need to add `scikit-build-core` to the host requirements

2024-07-10 15:20 UTC, dudoslav commented
And cmake

2024-07-11 15:26 UTC, jdblischak approved these changes
Looks good! I confirmed that `libtiledb.so` isn't getting copied into the Python installation directory

```
  *** Installing project into wheel...
  -- Install configuration: "RelWithDebInfo"
  -- Installing: /tmp/tmphwnd407a/wheel/platlib/tiledb/main.cpython-39-x86_64-linux-gnu.so
  -- Set non-toolchain portion of runtime path of "/tmp/tmphwnd407a/wheel/platlib/tiledb/main.cpython-39-x86_64-linux-gnu.so" to "/home/conda/feedstock_root/build_artifacts/tiledb-py_1720685810279/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib"
  -- Installing: /tmp/tmphwnd407a/wheel/platlib/tiledb/libtiledb.cpython-39-x86_64-linux-gnu.so
  -- Set non-toolchain portion of runtime path of "/tmp/tmphwnd407a/wheel/platlib/tiledb/libtiledb.cpython-39-x86_64-linux-gnu.so" to "/home/conda/feedstock_root/build_artifacts/tiledb-py_1720685810279/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib"
  -- Installing: /tmp/tmphwnd407a/wheel/platlib/tiledb/cc.cpython-39-x86_64-linux-gnu.so
  -- Set non-toolchain portion of runtime path of "/tmp/tmphwnd407a/wheel/platlib/tiledb/cc.cpython-39-x86_64-linux-gnu.so" to "/home/conda/feedstock_root/build_artifacts/tiledb-py_1720685810279/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib"
  *** Making wheel...
  *** Created tiledb-0.30.3.dev109+gd18362b1-cp39-cp39-linux_x86_64.whl...
  Building wheel for tiledb (pyproject.toml): finished with status 'done'
  Created wheel for tiledb: filename=tiledb-0.30.3.dev109+gd18362b1-cp39-cp39-linux_x86_64.whl size=31466445 sha256=8e0d9e2bb2e98f24384f25f562cf5b13f6a9e2a5c302dc34eefe4334b3dd72d2
  Stored in directory: /tmp/pip-ephem-wheel-cache-tbx35kw5/wheels/ae/cf/aa/c54d1dab71887bebd6619bd97ce2209e7935ce2ffdc4a8d52b
Successfully built tiledb
Installing collected packages: tiledb
Successfully installed tiledb-0.30.3.dev109+gd18362b1
```

2024-07-11 15:26 UTC, jdblischak commented on recipe/meta.yaml
> +  script: set "TILEDB_PATH=${PREFIX}" && {{ PYTHON }} -m pip install --no-build-isolation --no-deps --ignore-installed -v . # [win]
```suggestion
  script: set "TILEDB_PATH=${PREFIX}" && {{ PYTHON }} -m pip install --no-build-isolation --no-deps --ignore-installed -v .  # [win]
```

Not important for this test PR, but FYI this is what the linter is complaining about. It wants two spaces between the end of the line and the start of the jinja2 selector

2024-07-23 18:50 UTC, jdblischak commented on recipe/meta.yaml
> +  script: set "TILEDB_PATH=${PREFIX}" && {{ PYTHON }} -m pip install --no-build-isolation --no-deps --ignore-installed -v . # [win]
```suggestion
  script: set "TILEDB_PATH=%LIBRARY_PREFIX%" && {{ PYTHON }} -m pip install --no-build-isolation --no-deps --ignore-installed -v . # [win]
```

The env var on Windows is `%LIBRARY_PREFIX%`. This is what was used previously in this feedstock (see above), and is what is used in [tiledb-feedstock](https://github.com/conda-forge/tiledb-feedstock/blob/f7f5e16ba8630a7fd074ef1a8b456b3a28935172/recipe/bld.bat#L13)

2024-07-30 21:35 UTC, closed without merging